### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dieterhatnkleinen** [ivesdebruycker/maxcube#19]
I'm getting this output when I connect to my Max Cube via maxcube-cli:

> pimatic@machine:~$ node ./maxcube-cli.js 192.168.1.8
maxcube$
/home/pimatic/node_modules/maxcube/maxcube-commandparser.js:39
  return stringDecoder.write(Buffer.from(charArray));
                                    ^
TypeError: undefined is not a function
    at decodeStringPayload (/home/pimatic/node_modules/maxcube/maxcube-commandparser.js:39:37)
    at Object.parseCommandMetadata (/home/pimatic/node_modules/maxcube/maxcube-commandparser.js:76:21)
    at Object.parse (/home/pimatic/node_modules/maxcube/maxcube-commandparser.js:19:35)
    at MaxCubeLowLevel.<anonymous> (/home/pimatic/node_modules/maxcube/maxcube.js:41:46)
    at MaxCubeLowLevel.emit (events.js:107:17)
    at /home/pimatic/node_modules/maxcube/maxcube-lowlevel.js:39:14
    at Array.forEach (native)
    at Socket.<anonymous> (/home/pimatic/node_modules/maxcube/maxcube-lowlevel.js:35:16)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)`

**Comment by dieterhatnkleinen** [comment]
Fixed it by updating Nodejs to v7.
