### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'room_id' of undefined

### ISSUE THREAD

**Issue by dieterhatnkleinen** [ivesdebruycker/maxcube#20]
I have 5 Max Thermostats and a Max Cube installed.
4 of the thermostats came with the cube. They are working flawless with maxcube-cli.
I ordered a 5th one, which seems to be an older device with an older firmware.
I can see the devices' status, but I am not able to set its mode or temp.
I can set temp and modes via the official max software and via [eq3-max perl](https://github.com/Juerd/eq3-max)

Full error output:
`Unhandled rejection TypeError: Cannot read property 'room_id' of undefined
    at MaxCube.setTemperature (/home/pimatic/node_modules/maxcube/maxcube.js:161:110)
    at CommandInstance.<anonymous> (/home/pimatic/maxcube-cli.js:103:13)
    at Session.session.execCommandSet (/home/pimatic/node_modules/vorpal/dist/session.js:470:20)
    at Vorpal.vorpal._exec (/home/pimatic/node_modules/vorpal/dist/vorpal.js:960:18)
    at Vorpal.vorpal._execQueueItem (/home/pimatic/node_modules/vorpal/dist/vorpal.js:751:17)
    at Vorpal.vorpal._queueHandler (/home/pimatic/node_modules/vorpal/dist/vorpal.js:735:10)
    at Vorpal.vorpal.exec (/home/pimatic/node_modules/vorpal/dist/vorpal.js:682:10)
    at Vorpal.parse (/home/pimatic/node_modules/vorpal/dist/vorpal.js:166:12)
    at MaxCube.<anonymous> (/home/pimatic/maxcube-cli.js:6:10)
    at emitNone (events.js:86:13)
    at MaxCube.emit (events.js:188:7)
    at /home/pimatic/node_modules/maxcube/maxcube.js:33:14
    at tryCatcher (/home/pimatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pimatic/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pimatic/node_modules/bluebird/js/release/promise.js:614:10)`

**Comment by ivesdebruycker** [comment]
This error normally happens when you're using an unknown rf address, but if you're able tot retrieve the status of this device, that can't be the problem.
Could you test if flushing the device cache ('flush' in cli) solves the problem?

**Comment by Unkn0wn-MDCLXIV** [comment]
I did, and it does not seem to solve the problem.
